# Generated by Django 4.2.1 on 2023-06-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_blogpostuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='Posts.blogpostuser')),
                ('user_blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='Posts.blogpostuser')),
            ],
        ),
    ]
