# Generated by Django 4.2.1 on 2023-05-30 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_founded', models.IntegerField()),
                ('coverage_EU', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('max_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('year_of_birth', models.IntegerField()),
                ('total_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('takeoff_airport', models.CharField(max_length=255)),
                ('landing_airport', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='flights/')),
                ('airways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_ballons.airways')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_ballons.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Airways_Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_ballons.airways')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hot_air_ballons.pilot')),
            ],
        ),
    ]
