# Generated by Django 4.2.1 on 2023-06-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostuser',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpostuser',
            name='interests',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpostuser',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpostuser',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpostuser',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
